{"name": "用户注册登录查看-预期成功", "status": "broken", "statusDetails": {"message": "AttributeError: 'ResultBase' object has no attribute 'error'", "trace": "self = <testcases.user_service_test.test_userservice.TestRegLogList object at 0x109175850>\ntestcase_data = {'deviceID': 'decbb1ef-e41c-4cbd-9265-902415f00504', 'email': 'test256@premom.com', 'except_code': 0, 'except_msg': '登录成功', ...}\n\n    @allure.story(\"用例--注册/登录/查看--预期成功\")\n    @allure.description(\"该用例是针对 注册-登录-查看 场景的测试\")\n    @allure.issue(\"\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"用户注册登录查看-预期成功\")\n    @pytest.mark.multiple\n    def test_userservice_login(self, testcase_data):\n        \"\"\"\n        Test the user service login functionality with expected success.\n    \n        :param testcase_data: The data for the test case.\n        :type testcase_data: dict\n    \n        This function performs a test on the user service login functionality. It takes in the `testcase_data` parameter, which is a dictionary containing the necessary data for the test case. The `testcase_data` dictionary should have the following keys:\n    \n        - `email`: The email of the user.\n        - `password`: The password of the user.\n        - `deviceID`: The device ID of the user.\n        - `except_result`: The expected result of the test case.\n        - `except_code`: The expected code of the test case.\n        - `except_msg`: The expected message of the test case.\n    \n        The function starts by logging the beginning of the test case execution. It then calls the `webUserLogin` function with the provided `username`, `password`, and `deviceID`. The result of the function call is stored in the `result` variable.\n    \n        The function asserts that the `result.success` attribute is `True` and raises an error if it is not. It also asserts that the `result.success` attribute is equal to the `except_result` value and raises an error if it is not.\n    \n        The function logs the expected code and compares it with the actual code from the response. If they are not equal, an assertion error is raised. The function also asserts that the `except_msg` is present in the result message.\n    \n        Finally, the function logs the end of the test case execution.\n    \n        \"\"\"\n        username = testcase_data[\"email\"]\n        password = testcase_data[\"password\"]\n        deviceID = testcase_data[\"deviceID\"]\n        except_result = testcase_data[\"except_result\"]\n        except_code = testcase_data[\"except_code\"]\n        except_msg = testcase_data[\"except_msg\"]\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = webUserLogin(username, password, deviceID)\n>       assert result.success is True, result.error\nE       AttributeError: 'ResultBase' object has no attribute 'error'\n\ntestcases/user_service_test/test_userservice.py:50: AttributeError"}, "description": "该用例是针对 注册-登录-查看 场景的测试", "attachments": [{"name": "log", "source": "88e233e5-688e-46b8-8289-816f3fa1d703-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "80a82c08-e4a1-4e49-ba09-9412c476a5c6-attachment.txt", "type": "text/plain"}], "start": 1689837558352, "stop": 1689837558388, "uuid": "127354d5-95bd-48ba-85f8-3ddb637419ac", "historyId": "0283f9d4a052db405d74c5c4c7fca424", "testCaseId": "8427c5788e06b7f399d1191ad4a6d41b", "fullName": "testcases.user_service_test.test_userservice.TestRegLogList#test_userservice_login", "labels": [{"name": "feature", "value": "场景：用户注册-用户登录-查看用户"}, {"name": "story", "value": "用例--注册/登录/查看--预期成功"}, {"name": "severity", "value": "critical"}, {"name": "epic", "value": "针对业务场景的测试"}, {"name": "tag", "value": "multiple"}, {"name": "parentSuite", "value": "testcases.user_service_test"}, {"name": "suite", "value": "test_userservice"}, {"name": "subSuite", "value": "TestRegLogList"}, {"name": "host", "value": "MBP.local"}, {"name": "thread", "value": "86657-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.user_service_test.test_userservice"}], "links": [{"type": "test_case", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "name": "点击，跳转到对应BUG的链接地址"}]}