INFO     log:test_userservice.py:18 None