{"name": "用户注册登录查看-预期成功", "status": "broken", "statusDetails": {"message": "TypeError: step_1() missing 2 required positional arguments: 'sex' and 'address'", "trace": "self = <testcases.user_service_test.test_userservice.TestRegLogList object at 0x1029c9580>\ntestcase_data = {'deviceID': 'decbb1ef-e41c-4cbd-9265-902415f00504', 'email': 'test256@premom.com', 'except_code': 0, 'except_msg': '登录成功', ...}\n\n    @allure.story(\"用例--注册/登录/查看--预期成功\")\n    @allure.description(\"该用例是针对 注册-登录-查看 场景的测试\")\n    @allure.issue(\"\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"用户注册登录查看-预期成功\")\n    @pytest.mark.multiple\n    def test_userservice_login(self, testcase_data):\n        username = testcase_data[\"email\"]\n        password = testcase_data[\"password\"]\n        deviceID = testcase_data[\"deviceID\"]\n        except_result = testcase_data[\"except_result\"]\n        except_code = testcase_data[\"except_code\"]\n        except_msg = testcase_data[\"except_msg\"]\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = webUserLogin(username, password, deviceID)\n>       step_1(username, password, deviceID)\nE       TypeError: step_1() missing 2 required positional arguments: 'sex' and 'address'\n\ntest_userservice.py:41: TypeError"}, "description": "该用例是针对 注册-登录-查看 场景的测试", "steps": [{"name": "步骤1 ==>> 注册用户", "status": "broken", "statusDetails": {"message": "TypeError: step_1() missing 2 required positional arguments: 'sex' and 'address'\n", "trace": "  File \"/Users/elio/Library/Python/3.9/lib/python/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n"}, "parameters": [{"name": "username", "value": "'test256@premom.com'"}, {"name": "password", "value": "'123456'"}, {"name": "telephone", "value": "'decbb1ef-e41c-4cbd-9265-902415f00504'"}], "start": 1689585156563, "stop": 1689585156563}], "attachments": [{"name": "log", "source": "5cbc5650-dc96-4c07-bbed-d7f5dbe640bc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a58304d8-660a-4acd-bdfc-4dd2e2a14c40-attachment.txt", "type": "text/plain"}], "start": 1689585156471, "stop": 1689585156567, "uuid": "69d5d933-0e1f-4df0-bc03-034133771e32", "historyId": "0283f9d4a052db405d74c5c4c7fca424", "testCaseId": "8427c5788e06b7f399d1191ad4a6d41b", "fullName": "testcases.user_service_test.test_userservice.TestRegLogList#test_userservice_login", "labels": [{"name": "story", "value": "用例--注册/登录/查看--预期成功"}, {"name": "feature", "value": "场景：用户注册-用户登录-查看用户"}, {"name": "epic", "value": "针对业务场景的测试"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "multiple"}, {"name": "parentSuite", "value": "testcases.user_service_test"}, {"name": "suite", "value": "test_userservice"}, {"name": "subSuite", "value": "TestRegLogList"}, {"name": "host", "value": "MBP.local"}, {"name": "thread", "value": "68200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.user_service_test.test_userservice"}], "links": [{"type": "test_case", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "name": "点击，跳转到对应BUG的链接地址"}]}